version: '3'

services:
  database:
    image: postgis/postgis:13-3.4-alpine
    environment:
      POSTGRES_DB: pso
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
  database_test:
    image: postgis/postgis:13-3.4-alpine
    environment:
      POSTGRES_DB: pso_testing
      POSTGRES_USER: homestead
      POSTGRES_PASSWORD: secret
    ports:
      - '5433:5432'

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui

  redis:
    image: redis
    ports:
      - '6379:6379'

volumes:
  db-data:
