version: '3'

services:

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    volumes:
        - db-data:/var/lib/postgresql/data:rw
#        -  ./docker/db/data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
volumes:
  db-data:
