name: Laravel

on:
  push:
    branches:
      - main

jobs:
  phpunit:
    name: "Run PHP Unit tests & other checks"
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      postgres:
        image: postgis/postgis:15-master
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: gd, json, ldap, mbstring, mysql, pgsql, sqlite3, xml, xsl, zip, curl, soap, gmp, bcmath, imagick, intl, redis, imap
          coverage: none

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix styling

      - name: Install composer dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Prepare ENV
        run: |
          cp .env.ci .env

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Execute larastan
        run: vendor/bin/phpstan analyse

      - name: Execute tests
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: postgres
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
        run: vendor/bin/phpunit

